/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ResourceClaimSpec defines how a resource is to be allocated.
 */
export interface V1alpha1ResourceClaimSpec {
    /**
     * Allocation can start immediately or when a Pod wants to use the resource. \"WaitForFirstConsumer\" is the default.
     */
    allocationMode?: string;

    parametersRef?: models.V1alpha1ResourceClaimParametersReference;

    /**
     * ResourceClassName references the driver and additional parameters via the name of a ResourceClass that was created as part of the driver deployment.
     */
    resourceClassName: string;

}
