/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ValidatingAdmissionPolicySpec is the specification of the desired behavior of the AdmissionPolicy.
 */
export interface V1alpha1ValidatingAdmissionPolicySpec {
    /**
     * FailurePolicy defines how to handle failures for the admission policy. Failures can occur from invalid or mis-configured policy definitions or bindings. A policy is invalid if spec.paramKind refers to a non-existent Kind. A binding is invalid if spec.paramRef.name refers to a non-existent resource. Allowed values are Ignore or Fail. Defaults to Fail.
     */
    failurePolicy?: string;

    matchConstraints?: models.V1alpha1MatchResources;

    paramKind?: models.V1alpha1ParamKind;

    /**
     * Validations contain CEL expressions which is used to apply the validation. A minimum of one validation is required for a policy definition. Required.
     */
    validations: Array<models.V1alpha1Validation>;

}
