/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * AllocationResult contains attributed of an allocated resource.
 */
export interface V1alpha1AllocationResult {
    availableOnNodes?: models.V1NodeSelector;

    /**
     * ResourceHandle contains arbitrary data returned by the driver after a successful allocation. This is opaque for Kubernetes. Driver documentation may explain to users how to interpret this data if needed.  The maximum size of this field is 16KiB. This may get increased in the future, but not reduced.
     */
    resourceHandle?: string;

    /**
     * Shareable determines whether the resource supports more than one consumer at a time.
     */
    shareable?: boolean;

}
