/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ParamRef references a parameter resource
 */
export interface V1alpha1ParamRef {
    /**
     * Name of the resource being referenced.
     */
    name?: string;

    /**
     * Namespace of the referenced resource. Should be empty for the cluster-scoped resources
     */
    namespace?: string;

}
