/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ParamKind is a tuple of Group Kind and Version.
 */
export interface V1alpha1ParamKind {
    /**
     * APIVersion is the API group version the resources belong to. In format of \"group/version\". Required.
     */
    apiVersion?: string;

    /**
     * Kind is the API kind the resources belong to. Required.
     */
    kind?: string;

}
