/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * APIServiceStatus contains derived information about an API server
 */
export interface V1APIServiceStatus {
    /**
     * Current service state of apiService.
     */
    conditions?: Array<models.V1APIServiceCondition>;

}
