/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
 */
export interface V1AzureFileVolumeSource {
    /**
     * readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
     */
    readOnly?: boolean;

    /**
     * secretName is the  name of secret that contains Azure Storage Account Name and Key
     */
    secretName: string;

    /**
     * shareName is the azure share Name
     */
    shareName: string;

}
