/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account.
 */
export interface V1beta3Subject {
    group?: models.V1beta3GroupSubject;

    /**
     * `kind` indicates which one of the other fields is non-empty. Required
     */
    kind: string;

    serviceAccount?: models.V1beta3ServiceAccountSubject;

    user?: models.V1beta3UserSubject;

}
