/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * FlowSchemaStatus represents the current state of a FlowSchema.
 */
export interface V1beta2FlowSchemaStatus {
    /**
     * `conditions` is a list of the current states of FlowSchema.
     */
    conditions?: Array<models.V1beta2FlowSchemaCondition>;

}
