/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * PriorityLevelConfigurationStatus represents the current state of a \"request-priority\".
 */
export interface V1beta3PriorityLevelConfigurationStatus {
    /**
     * `conditions` is the current state of \"request-priority\".
     */
    conditions?: Array<models.V1beta3PriorityLevelConfigurationCondition>;

}
