/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
 */
export interface V1beta1EventSeries {
    /**
     * count is the number of occurrences in this series up to the last heartbeat time.
     */
    count: number;

    /**
     * lastObservedTime is the time when last Event from the series was seen before last heartbeat.
     */
    lastObservedTime: string;

}
