/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * DeploymentCondition describes the state of a deployment at a certain point.
 */
export interface V1DeploymentCondition {
    /**
     * Last time the condition transitioned from one status to another.
     */
    lastTransitionTime?: string;

    /**
     * The last time this condition was updated.
     */
    lastUpdateTime?: string;

    /**
     * A human readable message indicating details about the transition.
     */
    message?: string;

    /**
     * The reason for the condition\'s last transition.
     */
    reason?: string;

    /**
     * Status of the condition, one of True, False, Unknown.
     */
    status: string;

    /**
     * Type of deployment condition.
     */
    type: string;

}
