/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * IngressBackend describes all endpoints for a given service and port.
 */
export interface V1IngressBackend {
    resource?: models.V1TypedLocalObjectReference;

    service?: models.V1IngressServiceBackend;

}
