/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * IngressLoadBalancerIngress represents the status of a load-balancer ingress point.
 */
export interface V1IngressLoadBalancerIngress {
    /**
     * Hostname is set for load-balancer ingress points that are DNS based.
     */
    hostname?: string;

    /**
     * IP is set for load-balancer ingress points that are IP based.
     */
    ip?: string;

    /**
     * Ports provides information about the ports exposed by this LoadBalancer.
     */
    ports?: Array<models.V1IngressPortStatus>;

}
