/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * IngressLoadBalancerStatus represents the status of a load-balancer.
 */
export interface V1IngressLoadBalancerStatus {
    /**
     * Ingress is a list containing ingress points for the load-balancer.
     */
    ingress?: Array<models.V1IngressLoadBalancerIngress>;

}
