/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * IngressServiceBackend references a Kubernetes Service as a Backend.
 */
export interface V1IngressServiceBackend {
    /**
     * Name is the referenced service. The service must exist in the same namespace as the Ingress object.
     */
    name: string;

    port?: models.V1ServiceBackendPort;

}
