/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * JobCondition describes current state of a job.
 */
export interface V1JobCondition {
    /**
     * Last time the condition was checked.
     */
    lastProbeTime?: string;

    /**
     * Last time the condition transit from one status to another.
     */
    lastTransitionTime?: string;

    /**
     * Human readable message indicating details about last transition.
     */
    message?: string;

    /**
     * (brief) reason for the condition\'s last transition.
     */
    reason?: string;

    /**
     * Status of the condition, one of True, False, Unknown.
     */
    status: string;

    /**
     * Type of job condition, Complete or Failed.
     */
    type: string;

}
