/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * JobTemplateSpec describes the data a Job should have when created from a template
 */
export interface V1JobTemplateSpec {
    metadata?: models.V1ObjectMeta;

    spec?: models.V1JobSpec;

}
