/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * NetworkPolicyStatus describe the current state of the NetworkPolicy.
 */
export interface V1NetworkPolicyStatus {
    /**
     * Conditions holds an array of metav1.Condition that describe the state of the NetworkPolicy. Current service state
     */
    conditions?: Array<models.V1Condition>;

}
