/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * NodeCondition contains condition information for a node.
 */
export interface V1NodeCondition {
    /**
     * Last time we got an update on a given condition.
     */
    lastHeartbeatTime?: string;

    /**
     * Last time the condition transit from one status to another.
     */
    lastTransitionTime?: string;

    /**
     * Human readable message indicating details about last transition.
     */
    message?: string;

    /**
     * (brief) reason for the condition\'s last transition.
     */
    reason?: string;

    /**
     * Status of the condition, one of True, False, Unknown.
     */
    status: string;

    /**
     * Type of node condition.
     */
    type: string;

}
