/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.26.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * PersistentVolumeClaimCondition contails details about state of pvc
 */
export interface V1PersistentVolumeClaimCondition {
    /**
     * lastProbeTime is the time we probed the condition.
     */
    lastProbeTime?: string;

    /**
     * lastTransitionTime is the time the condition transitioned from one status to another.
     */
    lastTransitionTime?: string;

    /**
     * message is the human-readable message indicating details about last transition.
     */
    message?: string;

    /**
     * reason is a unique, this should be a short, machine understandable string that gives the reason for condition\'s last transition. If it reports \"ResizeStarted\" that means the underlying persistent volume is being resized.
     */
    reason?: string;

    status: string;

    type: string;

}
