/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ServiceStatus represents the current status of a service.
 */
export interface V1ServiceStatus {
    /**
     * Current service state
     */
    conditions?: Array<models.V1Condition>;

    loadBalancer?: models.V1LoadBalancerStatus;

}
