/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * UncountedTerminatedPods holds UIDs of Pods that have terminated but haven\'t been accounted in Job status counters.
 */
export interface V1UncountedTerminatedPods {
    /**
     * Failed holds UIDs of failed Pods.
     */
    failed?: Array<string>;

    /**
     * Succeeded holds UIDs of succeeded Pods.
     */
    succeeded?: Array<string>;

}
