export * from './AdmissionregistrationApi';
import { AdmissionregistrationApi } from './AdmissionregistrationApi';
export * from './AdmissionregistrationV1Api';
import { AdmissionregistrationV1Api } from './AdmissionregistrationV1Api';
export * from './ApiextensionsApi';
import { ApiextensionsApi } from './ApiextensionsApi';
export * from './ApiextensionsV1Api';
import { ApiextensionsV1Api } from './ApiextensionsV1Api';
export * from './ApiregistrationApi';
import { ApiregistrationApi } from './ApiregistrationApi';
export * from './ApiregistrationV1Api';
import { ApiregistrationV1Api } from './ApiregistrationV1Api';
export * from './ApisApi';
import { ApisApi } from './ApisApi';
export * from './AppsApi';
import { AppsApi } from './AppsApi';
export * from './AppsV1Api';
import { AppsV1Api } from './AppsV1Api';
export * from './AuthenticationApi';
import { AuthenticationApi } from './AuthenticationApi';
export * from './AuthenticationV1Api';
import { AuthenticationV1Api } from './AuthenticationV1Api';
export * from './AuthorizationApi';
import { AuthorizationApi } from './AuthorizationApi';
export * from './AuthorizationV1Api';
import { AuthorizationV1Api } from './AuthorizationV1Api';
export * from './AutoscalingApi';
import { AutoscalingApi } from './AutoscalingApi';
export * from './AutoscalingV1Api';
import { AutoscalingV1Api } from './AutoscalingV1Api';
export * from './AutoscalingV2beta1Api';
import { AutoscalingV2beta1Api } from './AutoscalingV2beta1Api';
export * from './AutoscalingV2beta2Api';
import { AutoscalingV2beta2Api } from './AutoscalingV2beta2Api';
export * from './BatchApi';
import { BatchApi } from './BatchApi';
export * from './BatchV1Api';
import { BatchV1Api } from './BatchV1Api';
export * from './BatchV1beta1Api';
import { BatchV1beta1Api } from './BatchV1beta1Api';
export * from './CertificatesApi';
import { CertificatesApi } from './CertificatesApi';
export * from './CertificatesV1Api';
import { CertificatesV1Api } from './CertificatesV1Api';
export * from './CoordinationApi';
import { CoordinationApi } from './CoordinationApi';
export * from './CoordinationV1Api';
import { CoordinationV1Api } from './CoordinationV1Api';
export * from './CoreApi';
import { CoreApi } from './CoreApi';
export * from './CoreV1Api';
import { CoreV1Api } from './CoreV1Api';
export * from './CustomObjectsApi';
import { CustomObjectsApi } from './CustomObjectsApi';
export * from './DiscoveryApi';
import { DiscoveryApi } from './DiscoveryApi';
export * from './DiscoveryV1Api';
import { DiscoveryV1Api } from './DiscoveryV1Api';
export * from './DiscoveryV1beta1Api';
import { DiscoveryV1beta1Api } from './DiscoveryV1beta1Api';
export * from './EventsApi';
import { EventsApi } from './EventsApi';
export * from './EventsV1Api';
import { EventsV1Api } from './EventsV1Api';
export * from './EventsV1beta1Api';
import { EventsV1beta1Api } from './EventsV1beta1Api';
export * from './FlowcontrolApiserverApi';
import { FlowcontrolApiserverApi } from './FlowcontrolApiserverApi';
export * from './FlowcontrolApiserverV1beta1Api';
import { FlowcontrolApiserverV1beta1Api } from './FlowcontrolApiserverV1beta1Api';
export * from './InternalApiserverApi';
import { InternalApiserverApi } from './InternalApiserverApi';
export * from './InternalApiserverV1alpha1Api';
import { InternalApiserverV1alpha1Api } from './InternalApiserverV1alpha1Api';
export * from './LogsApi';
import { LogsApi } from './LogsApi';
export * from './NetworkingApi';
import { NetworkingApi } from './NetworkingApi';
export * from './NetworkingV1Api';
import { NetworkingV1Api } from './NetworkingV1Api';
export * from './NodeApi';
import { NodeApi } from './NodeApi';
export * from './NodeV1Api';
import { NodeV1Api } from './NodeV1Api';
export * from './NodeV1alpha1Api';
import { NodeV1alpha1Api } from './NodeV1alpha1Api';
export * from './NodeV1beta1Api';
import { NodeV1beta1Api } from './NodeV1beta1Api';
export * from './OpenidApi';
import { OpenidApi } from './OpenidApi';
export * from './PolicyApi';
import { PolicyApi } from './PolicyApi';
export * from './PolicyV1Api';
import { PolicyV1Api } from './PolicyV1Api';
export * from './PolicyV1beta1Api';
import { PolicyV1beta1Api } from './PolicyV1beta1Api';
export * from './RbacAuthorizationApi';
import { RbacAuthorizationApi } from './RbacAuthorizationApi';
export * from './RbacAuthorizationV1Api';
import { RbacAuthorizationV1Api } from './RbacAuthorizationV1Api';
export * from './RbacAuthorizationV1alpha1Api';
import { RbacAuthorizationV1alpha1Api } from './RbacAuthorizationV1alpha1Api';
export * from './SchedulingApi';
import { SchedulingApi } from './SchedulingApi';
export * from './SchedulingV1Api';
import { SchedulingV1Api } from './SchedulingV1Api';
export * from './SchedulingV1alpha1Api';
import { SchedulingV1alpha1Api } from './SchedulingV1alpha1Api';
export * from './StorageApi';
import { StorageApi } from './StorageApi';
export * from './StorageV1Api';
import { StorageV1Api } from './StorageV1Api';
export * from './StorageV1alpha1Api';
import { StorageV1alpha1Api } from './StorageV1alpha1Api';
export * from './StorageV1beta1Api';
import { StorageV1beta1Api } from './StorageV1beta1Api';
export * from './VersionApi';
import { VersionApi } from './VersionApi';
export * from './WellKnownApi';
import { WellKnownApi } from './WellKnownApi';
export const APIS = [AdmissionregistrationApi, AdmissionregistrationV1Api, ApiextensionsApi, ApiextensionsV1Api, ApiregistrationApi, ApiregistrationV1Api, ApisApi, AppsApi, AppsV1Api, AuthenticationApi, AuthenticationV1Api, AuthorizationApi, AuthorizationV1Api, AutoscalingApi, AutoscalingV1Api, AutoscalingV2beta1Api, AutoscalingV2beta2Api, BatchApi, BatchV1Api, BatchV1beta1Api, CertificatesApi, CertificatesV1Api, CoordinationApi, CoordinationV1Api, CoreApi, CoreV1Api, CustomObjectsApi, DiscoveryApi, DiscoveryV1Api, DiscoveryV1beta1Api, EventsApi, EventsV1Api, EventsV1beta1Api, FlowcontrolApiserverApi, FlowcontrolApiserverV1beta1Api, InternalApiserverApi, InternalApiserverV1alpha1Api, LogsApi, NetworkingApi, NetworkingV1Api, NodeApi, NodeV1Api, NodeV1alpha1Api, NodeV1beta1Api, OpenidApi, PolicyApi, PolicyV1Api, PolicyV1beta1Api, RbacAuthorizationApi, RbacAuthorizationV1Api, RbacAuthorizationV1alpha1Api, SchedulingApi, SchedulingV1Api, SchedulingV1alpha1Api, StorageApi, StorageV1Api, StorageV1alpha1Api, StorageV1beta1Api, VersionApi, WellKnownApi];
